name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # shallow clone = build fails due to GitVersion

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: 'global.json'
      - name: Build
        run: dotnet build --configuration Release src/Web/Web.csproj
  
  docker-amd64:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Docker Build Environment
        id: meta
        uses: ./.github/actions/setup-docker-build-env
        with:
          use_qemu: false
      - name: Build Docker Container (Alpine - AMD64)
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: runner-alpine
          platforms: linux/amd64

  docker-arm64:
    runs-on: ubuntu-24.04-arm
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Docker Build Environment
        id: meta
        uses: ./.github/actions/setup-docker-build-env
        with:
          use_qemu: false
      - name: Build Docker Container (Alpine - ARM64)
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: runner-alpine
          platforms: linux/arm64

  docker-riscv64-armhf:
    if: false # Disabled until .NET supports RISCV64 properly
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Docker Build Environment
        id: meta
        uses: ./.github/actions/setup-docker-build-env
      - name: Build Docker Container (Alpine - RISCV64, ARMHF)
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: runner-alpine
          platforms: linux/riscv64,linux/arm/v6

  docker-ppc64le:
    if: false
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Docker Build Environment
        id: meta
        uses: ./.github/actions/setup-docker-build-env
      - name: Build Docker Container (Fedora - PPC64LE)
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: runner-fedora
          platforms: linux/ppc64le

  docker-s390x:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Docker Build Environment
        id: meta
        uses: ./.github/actions/setup-docker-build-env
      - name: Build Docker Container (Fedora - S390X)
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: runner-fedora
          platforms: linux/s390x