name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # shallow clone = build fails due to GitVersion

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: 'global.json'
      - name: Build
        run: dotnet build --configuration Release src/Web/Web.csproj
  
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Docker Build Environment
        id: meta
        uses: ./.github/actions/setup-docker-build-env
      - name: Build Docker Container (Alpine)
        uses: docker/build-push-action@v6
        with:
          context: .
          # push: true No binary releases yet
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: runner-alpine
          # I swear Microsoft's ARMHF .NET builds are broken...
          platforms: |
            linux/amd64,
            linux/arm64,
            linux/arm/v7,
            linux/riscv64
      - name: Build Docker Container (Fedora)
        uses: docker/build-push-action@v6
        with:
          context: .
          # push: true No binary releases yet
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: runner-fedora
          platforms: |
            linux/ppc64le,
            linux/s390x